version: '3.8'

networks:
  dmz-net:
    driver: bridge
  was-net:
    driver: bridge

services:
  frontend:
    build: ./frontend
    image: orix-msa/frontend:v1.0
    container_name: msa-frontend
    ports:
      - "80:80"
    networks:
      - dmz-net

  api-gw:
    build: ./api-gw
    image: orix-msa/api-gw:v1.0
    container_name: msa-api-gw
    depends_on:
      - lease
      - loan
      - exchange
    networks:
      - dmz-net
      - was-net

  lease:
    build: ./lease-service
    image: orix-msa/lease:v1.0
    container_name: msa-lease
    networks:
      - was-net

  loan:
    build: ./loan-service
    image: orix-msa/loan:v1.0
    container_name: msa-loan
    networks:
      - was-net

  exchange:
    build: ./exchange-service
    image: orix-msa/exchange:v1.0
    container_name: msa-exchange
    networks:
      - was-net
