server {
    listen 80;
    server_name localhost;

    # Lease Service Routing
    location /lease/ {
        proxy_pass http://lease:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 2s;
        proxy_read_timeout 3s;
    }

    # Loan Service Routing
    location /loan/ {
        proxy_pass http://loan:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 2s;
        proxy_read_timeout 3s;
    }

    # Exchange Rate Service Routing
    location /exchange/ {
        proxy_pass http://exchange:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 2s;
        proxy_read_timeout 3s;
    }


}
